apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wardk8s-manager-role
rules:
  - apiGroups:
      - ward.io
    resources:
      - securitypolicies
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ward.io
    resources:
      - securitypolicies/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wardk8s-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wardk8s-manager-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: wardk8s-system
